"""empty message

Revision ID: d68d78fc06da
Revises: faa0646f3c49
Create Date: 2026-05-13 17:24:39.037588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68d78fc06da'
down_revision = 'faa0646f3c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myplans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_data', sa.JSON(), nullable=True))
        batch_op.drop_column('is_workout')
        batch_op.drop_column('is_diet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myplans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_diet', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_workout', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('plan_data')

    # ### end Alembic commands ###
